const levels = [
    {
        ground: [
            { level: 10 },
            { level: 0, isSquareAngle: true },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: -3, isSquareAngle: true },
            { level: -2 },
            { level: -1 },
            { level: 2, isSquareAngle: true },
            { level: 2, isSquareAngle: true },
            { level: 3 },
            { level: 4, isSquareAngle: true },
            { level: 4 },
            { level: 0, isSquareAngle: true },
            { level: 0 },
            { level: 2 },
            { level: 2 },
            { level: 1 },
            { level: 1 },
            { level: 0 },
            { level: 0 },
            { level: 1 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 1 },
            { level: 2 },
            { level: 2 },
            { level: 1 },
            { level: 0 },
            { level: -1 },
            { level: -1 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 1 },
            { level: 2 },
            { level: 3 },
        ],
    }
]

export {
	levels
}
